---
title: "figures"
author: "Vienna Saccomanno"
date: "1/16/2020"
output:
  word_document: default
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(tinytex.verbose = TRUE)
```

## R Markdown

```{r}
library(dplyr)
library(tidyverse)
library(readr)
library(viridis)
library(hrbrthemes)
library(ggsci)
library(gridExtra)
library(ggplot2)
library(RColorBrewer)
library(cowplot)
library(egg)
library(gtable)

## For tables
library(stargazer)
library(formattable)
library(sjPlot)

```

###Making allocation bar charts on trends
```{r}
allo_cause <-read_csv("C:/Users/v.r.saccomanno/Desktop/Fed_Fish_Disasters/Final_figures/allocation_by_cause.csv")

allo_region<-read_csv("C:/Users/v.r.saccomanno/Desktop/Fed_Fish_Disasters/Final_figures/allocation_by_region.csv")
#View(allo_region)

#Changing legend order
levels(allo_cause$Cause)
levels(allo_region$Region)
allo_cause$Cause<- factor(allo_cause$Cause, levels = c("Anthropogenic", "Environmental", "Combination of both", "To be determined"))
allo_region$Region<- factor(allo_region$Region, levels = c("Alaska", "Greater Atlantic", "Pacific Islands", "Southeast", "West Coast", "To be determined"))

#allocation by cause
cause_p0 <- ggplot(allo_cause, aes(fill= Cause, y=Allocation, x=Year))+
  geom_bar(position = "stack", stat= "identity")+
  scale_y_continuous(labels = scales::dollar)+
  scale_x_continuous(breaks=c(1994, 2000, 2005, 2010, 2015, 2020))+
  labs(x="", y= "Allocation", subtitle= "B")+
  scale_fill_brewer(palette = "YlOrBr")+
  theme_classic()


#allocation by region
region_p0 <- ggplot(allo_region, aes(fill= Region, y=Allocation, x=Year))+
  geom_bar(position = "stack", stat= "identity")+
  scale_y_continuous(labels = scales::dollar)+
  scale_x_continuous(breaks=c(1994, 2000, 2005, 2010, 2015, 2020))+
  labs(x="Year", y= "Allocation", subtitle= "A")+
  scale_fill_brewer(palette = "YlGnBu")+
  theme_classic()

#Combining plots
A <- ggplotGrob(region_p0)
B <- ggplotGrob(cause_p0)

# Set the widths
A$widths <- B$widths

# Arrange the two charts.
# The legend boxes are centered

grid.arrange(A, B, nrow = 2)
p<- arrangeGrob(A,B) 
ggsave("Fig1.png",width = 6, height = 5, p)

```


###Making frequency and state-year bar charts on trends
```{r}

#By Region
freq_region <- read_csv("C:/Users/v.r.saccomanno/Desktop/Fed_Fish_Disasters/Final_figures/frequency_by_region.csv")
styr_region<- read_csv("C:/Users/v.r.saccomanno/Desktop/Fed_Fish_Disasters/Final_figures/stateyear_by_region.csv")


#By cause
freq_cause <- read_csv("C:/Users/v.r.saccomanno/Desktop/Fed_Fish_Disasters/Final_figures/frequency_by_cause.csv")
styr_cause<- read_csv("C:/Users/v.r.saccomanno/Desktop/Fed_Fish_Disasters/Final_figures/stateyear_by_cause.csv")
#View(styr_cause)

#Changing legend order
levels(freq_cause$Cause)
styr_cause$Cause<- factor(styr_cause$Cause, levels = c("Anthropogenic", "Environmental", "Combination of both"))
freq_cause$Cause<- factor(freq_cause$Cause, levels = c("Anthropogenic", "Environmental", "Combination of both"))


#Frequency by Region -A
region_p3 <- ggplot(freq_region, aes(fill= Region, y=Frequency, x=Year))+
  geom_bar(position = "stack", stat= "identity")+
  ylim(0, 10)+
  scale_x_continuous(breaks=c(1994, 2000, 2005, 2010, 2015, 2020))+
  scale_fill_brewer(palette = "YlGnBu")+
  labs(x="Year", y= "Disaster frequency", subtitle= "A")+
  theme_classic()

#Frequency by cause -B
cause_p3 <- ggplot(freq_cause, aes(fill= Cause, y=Frequency, x=Year))+
  geom_bar(position = "stack", stat= "identity")+
  ylim(0, 10)+
  scale_x_continuous(breaks=c(1994, 2000, 2005, 2010, 2015, 2020))+
  scale_fill_brewer(palette = "YlOrBr")+
  labs(x="Year", y= "Disaster frequency", subtitle= "B")+
  theme_classic()


#Stateyear by Region - C
region_p5 <- ggplot(styr_region, aes(fill= Region, y=StateYears, x=Year))+
  geom_bar(position = "stack", stat= "identity")+
  ylim(0, 10.0)+
  #scale_y_continuous(breaks=seq(0,12,2.5), labels = scales::number_format(accuracy = 0.1))+
  scale_x_continuous(breaks=c(1994, 2000, 2005, 2010, 2015, 2020))+
  scale_fill_brewer(palette = "YlGnBu")+
  labs(x="Year", y= "State-year frequency", subtitle= "C")+
  theme_classic()

#Stateyear by cause - D
cause_p5 <- ggplot(styr_cause, aes(fill= Cause, y=StateYears, x=Year))+
  geom_bar(position = "stack", stat= "identity")+
  ylim(0, 10.0)+
  #scale_y_continuous(breaks=seq(0,12,2.0))+
  scale_x_continuous(breaks=c(1994, 2000, 2005, 2010, 2015, 2020))+
  scale_fill_brewer(palette = "YlOrBr")+
  labs(x="Year", y= "State-year frequency", subtitle= "D")+
  theme_classic()

#Combining plots
pA <- ggplotGrob(region_p3)
pB <- ggplotGrob(cause_p3)
pC <- ggplotGrob(region_p5)
pD <- ggplotGrob(cause_p5)

# Set the widths
pA$widths <- pB$widths
pC$widths <- pD$widths
#pA$widths <- pC$widths

# Arrange the two charts.
# The legend boxes are centered

grid.arrange(pA, pC, pB, pD, nrow = 2)

#grid.arrange(region_p3, region_p5, cause_p3, cause_p5)
g<- arrangeGrob(pA, pC,pB, pD)
ggsave("Fig2.png",width = 10, height = 5, g)
```



