---
title: "Federal Fisheries Disasters Revenue Loss Economic Estimate"
author: "Vienna Saccomanno"
date: "2/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#This .Rmd contains the analysis for the bootstrap analysis to obtain the CI for the median, direct revenue loss in a disaster year
```



```{r}
#Attach packages

library(ggplot2)
library(readr)
library(tidyverse)
library(packHV)
library(boot)
library(naniar)

```


```{r}
#Load data
econ_raw <- read_csv("econ_est_R_2.csv")
View(econ_raw)

```

### 1. Data wrangling and exploration
```{r}
# Exploratory graph
ggplot(econ_raw, aes(x = dollar_diff_real)) +
  geom_histogram(bins = 5) +
  theme_light()
#Non-normal distribution

#Q-Q plots
qqnorm(econ_raw$dollar_diff_real)
#Curving off at the extremities = data have more extreme values that we'd expect if they truly came from a normal distribution

#Test for normality
shapiro.test(econ_raw$dollar_diff_real)
#p-value = 2.625e-11 = statistically different from a normal distribution


# Pull revenue change (real) as a vector (removes the 8 NAs) for all disasters for which there is data
econ_change <- econ_raw%>% 
  pull(dollar_diff_real)%>%
  na.omit

View(econ_change)
summary(econ_change)
#      Min.    1st Qu.     Median       Mean    3rd Qu.       Max. 
#-300618829  -19603118   -3548578  -35630166    -421652  139911239 
sum(econ_change) -#2,814,783,100


# Pull revenue change (real) as a vector (removes the 8 NAs); isolate only loss years
econ_change_loss <- econ_raw%>% 
  filter(dollar_diff_real < 0)%>%
  pull(dollar_diff_real)%>%
  na.omit
View(econ_change_loss)

summary(econ_change_loss)
#      Min.    1st Qu.     Median       Mean    3rd Qu.       Max. 
#-300618829  -57366274  -11557915  -52042019   -1691004    -244000 

sum(econ_change_loss) 
# -$3,226,605,152

```

###2. Use the set.seed function to ensure all results, figures, etc are reproducible.
```{r}
set.seed(123)
```


###3. Create a function for bootstrapping analysis:

```{r}

#### Create a function to calculate the MEAN of varying vectors (x) of index (i) - all disasters

mean_fun <- function (x,i) {mean(x[i])}

# 100000 bootstrap samples:
boot_mean_100000 <- boot(econ_change, mean_fun, R = 100000)

ggplot() +
  aes(boot_mean_100000$t) +
  geom_histogram()

boot_mean_100000$t0 # to report the mean of the original sample =-$35,630,166
boot_mean_100000 # to report bias, SE
#Bias (difference between original sample mean and bootstrapped sampling mean)= $51,693.04
#Std. error (SD of bootstrapped sampling distribution)=$9,296,369


################

#### Create a function to calculate the MEDIAN of varying vectors (x) of index (i) - all disasters
median_fun <- function (x,i) {median(x[i])}

# 100000 bootstrap samples:
boot_med_100000 <- boot(econ_change, median_fun, R = 100000)

ggplot() +
  aes(boot_med_100000$t) +
  geom_histogram()

boot_med_100000$t0 # Median of the original sample = -$3548578
boot_med_100000 # to report bias, SE
#Bias (difference between original sample median and bootstrapped sampling median)=$-702,981.6
#Std. error (SD of bootstrapped sampling distribution)= $2,455,482


################

#### Create a function to calculate the MEDIAN of varying vectors (x) of index (i) - only loss years disasters

median_fun <- function (x,i) {median(x[i])}

# 100000 bootstrap samples:
boot_med_loss_100000 <- boot(econ_change_loss, median_fun, R = 100000)

ggplot() +
  aes(boot_med_loss_100000$t) +
  geom_histogram()

boot_med_loss_100000$t0 # Median of the original sample (loss years only) = -$11,557,915
boot_med_loss_100000 # to report bias, SE
#Bias (difference between original sample median and bootstrapped sampling median)= $1,184,241
#Std. error (SD of bootstrapped sampling distribution)= $3,319,164
```


###4. Find a bootstrapped confidence interval:

```{r}
#95% CI for mean statistic- all disasters
boot.ci(boot_mean_100000, conf = 0.95, type = 'basic') #'basic' = compute differences between each bootstrap replication and t0 and use percentiles of their distribution. 

#Intervals : 
#Level      Basic         
#95%   (-53036226, -16694819 ) 

# Mean, direct revenue loss in a disaster year is -$35,630,166 ($US2019) (n=78), with a boot strapped 95% confidence interval of [(-$53,036,226, -$16,694,819)(n= 100,000 bootstrap samples).

#######################

#95% CI for median statistic - all disasters
boot.ci(boot_med_100000, conf = 0.95, type = 'basic') #'basic' = compute differences between each bootstrap replication and t0 and use percentiles of their distribution. 

#Intervals : 
#Level      Basic         
#95%   (-$5,560,384,  $4,791,675 ) 

# Median, direct revenue loss in a disaster year is -$3,548,578 ($US2019) (n=78), with a boot strapped 95% confidence interval of [(-$5,560,384,  $4,791,675 ) ] (n= 100,000 bootstrap samples).

#######################

#95% CI for median statistic - loss years only disasters

boot.ci(boot_med_loss_100000, conf = 0.95, type = 'basic') #'basic' = compute differences between each bootstrap replication and t0 and use percentiles of their distribution. 

#Intervals : 
#Level      Basic         
#95%   (-$18,713,497,  -$7,635,949) 

# Median, direct revenue loss in a disaster year is -$11,557,915 ($US2019) (n=62), with a boot strapped 95% confidence interval of [(-$18,713,497,  -$7,635,949)] (n= 100,000 bootstrap samples).
  
```



