---
title: "main-tables"
author: "Vienna Saccomanno"
date: "4/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, warning=FALSE, message=FALSE}


#Attach packages
library(readr)
library(knitr)
library(kableExtra)
library(tidyverse)
library(dplyr)
library(magick)
library(webshot)

#webshot::install_phantomjs()

```


```{r, warning=FALSE, message=FALSE}
#Load data

#Revenue Loss Data
rev_loss <- read_csv("C:/Users/v.r.saccomanno/Desktop/Fed_Fish_Disasters/Final_figures/rev_loss_table.csv")
View(rev_loss)

#Allocation table data
allo_table <- read_csv("C:/Users/v.r.saccomanno/Desktop/Fed_Fish_Disasters/Final_figures/allocation_table.csv")

```


```{r, warning=FALSE, message=FALSE}
#Create Revenue Loss Table

kable(rev_loss, "latex", booktabs = T)%>%
  kable_styling(latex_options = c("striped", "scale_down"), font_size = 5) %>%
  row_spec(0, bold= T)%>%
  column_spec(1, bold=T)%>%
  column_spec(7, italic =T)%>%
  row_spec(4, italic = T) %>%
  save_kable("revenue_loss_table.pdf")
  #as_image()

```
```{r, warning=FALSE, message=FALSE}
#Create Allocaiton Table

kable(allo_table, "latex", booktabs = T)%>%
  kable_styling(latex_options = c("striped", "scale_down"), font_size = 5) %>%
  row_spec(0, bold= T)%>%
  column_spec(1, bold=T)%>%
  row_spec(5, italic = T) %>%
  save_kable("allocaiton_table.pdf")
  #as_image()

```